name: Build, analyze and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ape
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout maven settings
        uses: actions/checkout@v3
        with:
          repository: Ma-Vin/de.ma_vin.maven
          token: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
          path: maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          java-package: jdk
          cache: 'maven'
      - name: Build ape
        env:
          GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        run: mvn -B clean install --file main/pom.xml --settings maven/settings.xml
      - name: delete old versions
        uses: actions/delete-package-versions@v2
        with:
          package-name: de.ma_vin.ape.ape
          min-versions-to-keep: 0
          delete-only-pre-release-versions: "true"
          token: ${{ secrets.APE_GITHUB_PACKAGES_PAT }}
      - name: Deploy ape
        env:
          GITHUB_PACKAGES_USERNAME: ${{ secrets.APE_GITHUB_PACKAGES_USER }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.APE_GITHUB_PACKAGES_PAT }}
          GITHUB_TOKEN: ${{ secrets.APE_DEPENDENCY_BUILD_PAT }}
        run: mvn -B deploy --file main/pom.xml --settings maven/settings.xml
      - name: create trigger
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.APE_WEBHOOK_PAT }}" https://api.github.com/repos/Ma-Vin/de.ma_vin.ape.utils/actions/workflows/maven.yml/dispatches -d '{"ref": "${{ github.ref }}", "inputs": { "branch": "${{ github.ref_name }}" } }'